# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.box_version = "3.4.4"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.memory = 2024
    v.cpus = 2
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "file", source: "./", destination: "/home/vagrant/p2"
  
  config.vm.boot_timeout = 1000
  config.vm.define "ophuongS" do |control|
    control.vm.hostname = "ophuongS"
    control.vm.network "private_network", ip: "192.168.42.110"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "ophuongS"]
    end
    control.vm.provision "shell", inline: <<-SHELL
      export INSTALL_K3S_EXEC="--write-kubeconfig /home/vagrant/.kube/config --write-kubeconfig-mode 666 --node-external-ip 192.168.42.110 --tls-san 192.168.42.110"
      curl -sfL https://get.k3s.io | sh -
      systemctl stop firewalld
      systemctl disable firewalld
      sleep 25
      echo "LOADING..."
      SHELL
    control.vm.provision "shell", inline: <<-SHELL
      /usr/local/bin/kubectl apply -f ./p2/scripts/ingress.yaml
      /usr/local/bin/kubectl apply -f ./p2/scripts/app3.yaml
      /usr/local/bin/kubectl apply -f ./p2/scripts/app1.yaml
      /usr/local/bin/kubectl apply -f ./p2/scripts/app2.yaml
    SHELL
  end
end
