# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.memory = 1024
    v.cpus = 2
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.define "eklompusS" do |control|
    control.vm.hostname = "eklompusS"
    control.vm.network "private_network", ip: "192.168.42.110"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "eklompusS"]
    end
    control.vm.provision "shell", inline: <<-SHELL
      export INSTALL_K3S_EXEC="--write-kubeconfig /home/vagrant/.kube/config --write-kubeconfig-mode 666 --node-external-ip 192.168.42.110 --tls-san 192.168.42.110"
      curl -sfL https://get.k3s.io | sh -
      NODE_TOKEN="/var/lib/rancher/k3s/server/node-token"
      while [ ! -e ${NODE_TOKEN} ]
      do
        sleep 2
      done
      cat ${NODE_TOKEN}
      cp ${NODE_TOKEN} /home/vagrant/
      chown vagrant:vagrant /home/vagrant/node-token
    SHELL
  end
  config.vm.define "eklompusSW" do |control|
    control.vm.hostname = "eklompusSW"
    control.vm.network "private_network", ip: "192.168.42.111"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "eklompusSW"]
    end
    control.vm.provision "master-key", type: "file", source: ".vagrant/machines/eklompusS/virtualbox/private_key", destination: "/home/vagrant/.ssh/master.key"
    control.vm.provision "shell", inline: <<-SHELL
      scp -i /home/vagrant/.ssh/master.key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no vagrant@192.168.42.110:/home/vagrant/node-token /home/vagrant/
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.42.110:6443 K3S_TOKEN=$(cat /home/vagrant/node-token) sh -
    SHELL
  end
end
