apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
  labels:
    app: hello-kubernetes2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-kubernetes2
  template:
    metadata:
      labels:
        app: hello-kubernetes2
    spec:
      containers:
      - name: hello-kubernetes2
        image: paulbouwer/hello-kubernetes:1.10
        ports:
        - containerPort: 82